# Generated by Django 5.2.8 on 2025-11-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_date_members_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
